apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: cluster-registry:32000/accounts:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URI
          value: postgresql://postgres:postgres@postgresql:5432/postgres
        - name: PORT
          value: "8080"
